from typing import Optional, List, Dict, Any, Literal
from datetime import datetime, timezone
from uuid import UUID, uuid4
from pydantic import BaseModel, Field

class ExecutiveBrief(BaseModel):
    trade_id: UUID
    user_id: str
    symbol: str
    timestamp: datetime
    final_verdict: str
    consensus_score: str
    sentiment_layer: dict[str, str]
    strategy_layer: dict[str, str]
    math_layer: dict[str, str]
    risk_verification: dict[str, str]
    decision_basis: str


# ──────────────────────────────────────────────
#  AccountHealth — how is the trader's account doing?
# ──────────────────────────────────────────────

class AccountHealth(BaseModel):
    """
    A real-time snapshot of the trader's account.
    If is_locked is True, the system has shut down
    trading for safety — the lock_reason explains why.
    """
    balance: float = Field(
        ...,
        ge=0,
        description="Current account balance in USD",
    )
    equity: float = Field(
        ...,
        ge=0,
        description="Balance plus/minus unrealised P&L",
    )
    daily_drawdown_pct: float = Field(
        default=0.0,
        ge=0,
        le=100,
        description="How much the account has lost today as a percentage",
    )
    is_locked: bool = Field(
        default=False,
        description="True if the kill-switch has been triggered",
    )
    lock_reason: Optional[str] = Field(
        default=None,
        description="Why the account was locked, e.g. 'Daily drawdown exceeded 3%'",
    )
    lock_expiry: Optional[datetime] = Field(
        default=None,
        description="When the lock will automatically lift (UTC)",
    )


# ──────────────────────────────────────────────
#  RiskDecision — the risk engine's final word
# ──────────────────────────────────────────────

class RiskDecision(BaseModel):
    """
    After the HardRiskKernel inspects a TradeOrder, it
    returns this. If approved is False, the trade is dead —
    no override, no exception, no workaround.
    """
    id: UUID = Field(
        default_factory=uuid4,
        description="Unique ID for this risk decision (for audit trail)",
    )
    approved: bool = Field(
        ...,
        description="True if the trade passed all risk checks",
    )
    calculated_lot_size: float = Field(
        ...,
        ge=0,
        description="The lot size the risk engine calculated as safe",
    )
    stop_loss: Optional[float] = Field(
        default=None,
        description="The stop-loss price approved by the risk engine",
    )
    take_profit: Optional[float] = Field(
        default=None,
        gt=0,
        description="The take-profit price, if provided",
    )
    expected_price: float = Field(
        default=0.0,
        description="The market price at the exact millisecond the Risk Engine approved the trade.",
    )
    use_virtual_stops: bool = Field(
        default=True,
        description="If true, SL/TP are withheld from the broker API and executed from memory.",
    )
    rejection_reason: Optional[str] = Field(
        default=None,
        description="If rejected, the exact reason why",
    )
    vetoing_agents: list[str] = Field(
        default_factory=list,
        description="List of agent names (e.g. ['TITAN', 'SAGE']) that vetoed this trade.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this decision was made (UTC)",
    )


# ──────────────────────────────────────────────
#  The Trader's Constitution — User-Defined Safety
# ──────────────────────────────────────────────

class ConstitutionRule(BaseModel):
    """
    A single mandate set by the trader or generated by the Auditor.
    """
    id: UUID | str = Field(default_factory=uuid4)
    name: str = Field(default="Legacy Rule", description="Short name, e.g., 'No Overtrading'")
    description: str = Field(..., description="Plain English description of the rule")
    rule_type: str = Field(
        default="custom",
        description="Type of rule: 'max_daily_trades', 'min_consensus', 'forbidden_hours', 'custom'"
    )
    parameter: float = Field(
        default=0.0,
        description="The numerical threshold (e.g., 3 trades, 80% consensus)"
    )
    condition_payload: dict = Field(
        default_factory=dict,
        description="JSON object holding dynamic autonomous rules (e.g. {'symbol': 'EUR/USD', 'max_spread_allowed': 3.5})"
    )
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class AppConstitution(BaseModel):
    """
    The full document governing the trader's behavior. The Hard Risk Kernel
    will read this and physically prevent the trader from breaking it.
    """
    rules: list[ConstitutionRule] = Field(default_factory=list)
    daily_trades_count: int = Field(default=0, ge=0)
    last_reset_date: str = Field(default="")  # YYYY-MM-DD

# ──────────────────────────────────────────────
#  The Auditor — Post-Mortem Analysis
# ──────────────────────────────────────────────

class PostMortemRequest(BaseModel):
    trade_id: str
    symbol: str
    direction: str
    entry_price: float
    exit_price: float
    pnl: float
    user_notes: Optional[str] = None
    
class PostMortemResult(BaseModel):
    mistake_dna: str = Field(..., description="Categorized mistake e.g., 'FOMO', 'Revenge Trading', 'Bad Setup', 'Systematic Loss'")
    analysis: str = Field(..., description="Harsh, truth-telling analysis of the trade")
    suggested_rule: Optional[ConstitutionRule] = Field(
        default=None, 
        description="A proposed Constitution rule to prevent this from happening again."
    )

# ──────────────────────────────────────────────
#  The Autopilot — Auto-Execution Engine
# ──────────────────────────────────────────────

class BrokerRiskConfig(BaseModel):
    """Individual per-broker risk allocation & asset-class filter."""
    broker_id: str = Field(..., description="Unique broker identifier e.g. 'ftmo_1', 'exness'")
    account_name: str = Field(default="", description="Account alias e.g. 'FTMO $100k Challenge'")
    balance: float = Field(default=10000.0, ge=0.0, description="Cached balance for dynamic lot calculation")
    risk_percent: float = Field(default=1.0, ge=0.1, le=5.0, description="Custom risk % for this specific account")
    daily_drawdown_limit: float = Field(default=3.0, ge=1.0, le=10.0, description="Custom daily loss cap %")
    allowed_asset_classes: list[str] = Field(
        default_factory=lambda: ["FOREX", "METALS", "CRYPTO", "INDICES"],
        description="Asset categories allowed to trade on this broker"
    )
    is_active: bool = Field(default=True, description="Enable or disable execution for this broker")


class AutopilotConfig(BaseModel):
    """
    The strict configuration for the Auto-Execution engine.
    Unlocked only when the user proves they are a safe trader.
    """
    enabled: bool = Field(
        default=False, 
        description="True if the user has unlocked and enabled Autopilot."
    )
    tier: str = Field(
        default="observer",
        description="The user's current subscription tier, cached for priority routing."
    )
    whitelisted_pairs: list[str] = Field(
        default_factory=list, 
        description="List of approved pairs, e.g. ['XAU/USD', 'EUR/USD']."
    )
    active_hours_start_utc: int = Field(
        default=0, ge=0, le=23, 
        description="Hour to start auto-trading (UTC)."
    )
    active_hours_end_utc: int = Field(
        default=23, ge=0, le=23, 
        description="Hour to stop auto-trading (UTC)."
    )
    preferred_lot_size: float = Field(
        default=0.01, ge=0.01, le=10.0,
        description="The user's preferred position size. Default 0.01 micro-lots."
    )
    broker_overrides: list[BrokerRiskConfig] = Field(
        default_factory=list,
        description="Per-broker individual risk allocations and asset class filters."
    )
    active_allocations: dict[str, float] = Field(
        default_factory=dict, 
        description="Maps symbol to exact calculated lot size during master block execution."
    )
    max_concurrent_positions: int = Field(
        default=3, ge=1, le=10,
        description="Maximum number of simultaneous auto-trades allowed. Prevents overexposure."
    )
    assist_mode: bool = Field(
        default=False,
        description="If True, Sniper arms but waits for user confirmation before executing."
    )
    
    # ── Tier Gating & Trade Management Features ──
    max_connected_brokers: int = Field(
        default=1, ge=1, le=5,
        description="Max brokers allowed: Core=1, Precision=2, Sovereign=5."
    )
    session_armed: bool = Field(
        default=False,
        description="Precision tier: True when user has armed an active trading session."
    )
    session_armed_until: Optional[str] = Field(
        default=None,
        description="ISO UTC timestamp when the Precision tier armed session expires and disarms."
    )
    auto_breakeven_enabled: bool = Field(
        default=False,
        description="Precision & Sovereign: Auto-moves Stop Loss to breakeven after +1.5R gain."
    )
    auto_partial_take_profit: bool = Field(
        default=False,
        description="Precision & Sovereign: Auto-banks 50% profit at Target 1."
    )
    dynamic_trailing_stop: bool = Field(
        default=False,
        description="Sovereign tier ONLY: Dynamic ATR Chandelier trailing stop on runners."
    )
    is_24_7_autonomous: bool = Field(
        default=False,
        description="Sovereign tier ONLY: 100% hands-free unattended 24/5 cloud daemon execution."
    )
    
    # Institutional Compounding Engine
    compounding_mode: Literal["OFF", "DYNAMIC SCALING", "INSTITUTIONAL COMPOUNDING"] = Field(
        default="OFF", 
        description="OFF, DYNAMIC SCALING, or INSTITUTIONAL COMPOUNDING"
    )
    predator_mode: bool = Field(
        default=False,
        description="ALPHA MODE: Switches from defense to predator after a win. Removes win-streak caps and scales risk aggressively."
    )
    simulated_equity: float = Field(
        default=100.0, 
        description="Starting simulated capital for compounding math."
    )
    peak_equity: float = Field(
        default=100.0, 
        description="Highest equity reached, used for drawdown calculation."
    )
    current_drawdown_pct: float = Field(
        default=0.0, 
        description="Drawdown from peak equity."
    )
    consecutive_wins: int = Field(
        default=0, 
        description="Win streak tracker."
    )
    consecutive_losses: int = Field(
        default=0, 
        description="Loss streak tracker."
    )
    
    # Eligibility & State Tracking
    last_losing_trade_timestamp: Optional[datetime] = Field(
        default=None, 
        description="Rolling 4-hour cooldown tracking."
    )
    max_daily_auto_trades: int = Field(
        default=2, ge=0, 
        description="Maximum number of daily auto-trades allowed per user."
    )
    daily_auto_trades_count: int = Field(
        default=0, ge=0, 
        description="Current count of daily trades."
    )
    last_trade_date: Optional[str] = Field(
        default=None,
        description="ISO date string (YYYY-MM-DD) of last auto-trade. Used to reset daily counter at midnight UTC."
    )
    weekly_auto_trades_count: int = Field(
        default=0, ge=0, 
        description="Max 5 per week."
    )
    frozen: bool = Field(
        default=False, 
        description="True if a broker API timeout occurred. Requires manual unfreeze."
    )
    open_auto_positions: list[str] = Field(
        default_factory=list,
        description="Symbols with currently open auto-execution positions. Prevents duplicate entries."
    )
    last_week_reset_date: Optional[str] = Field(
        default=None,
        description="ISO week string (YYYY-WXX) of last weekly counter reset. Used to reset weekly_auto_trades_count at week boundary."
    )
    account_balance: float = Field(
        default=10_000.0, ge=0.0,
        description="User account balance or paper demo capital in USD."
    )
    risk_per_trade: float = Field(
        default=1.0, ge=0.1, le=10.0,
        description="Target risk percentage per trade (0.1% to 10.0%)."
    )
    daily_loss_usd: float = Field(
        default=0.0, ge=0.0,
        description="Cumulative realized daily loss in USD for the 3% daily drawdown kill-switch."
    )
    max_risk_per_trade_pct: float = Field(
        default=1.0, ge=0.1, le=10.0,
        description="Maximum risk percentage per trade cap."
    )


# ──────────────────────────────────────────────
#  MAM / Master Ledger Execution & Dark Pool
# ──────────────────────────────────────────────

from mam_models import (
    FirmInventory,
    MasterTradeReceipt,
    LedgerDistributionTask,
    Watchlist,
)



